name: clock
description: Humanbeans Flutter Clock Challange Submission

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.0
  supernova_flutter_ui_toolkit: ^0.0.2
  flare_flutter: ^1.8.3
  path_provider: ^1.5.1
  flutter_launcher_icons: ^0.7.4



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/rive/Bird_Final_2.flr
    - assets/rive/Light_Final.flr

    - assets/images/Pngs_Flat_0003_Bird_Shine_Color_Dodge.png
    - assets/images/Pngs_Flat_0001_Texture_Screen.png
    - assets/images/Pngs_Flat_0002_Texture_Multiply.png

    - assets/images/Pngs_Flat_0007_F_B_Left.png
    - assets/images/Pngs_Flat_0008_F_B_Left_2.png
    - assets/images/Pngs_Flat_0004_F_Leaf_L_1.png
    - assets/images/Pngs_Flat_0005_F_Leaf_L_2.png
    - assets/images/Pngs_Flat_0006_F_Leaf_L_3.png

    - assets/images/Pngs_Flat_0033_B_Br_Left.png
    - assets/images/Pngs_Flat_0034_B_Br_Left_1.png
    - assets/images/Pngs_Flat_0032_B_Leaf_L_1.png
    - assets/images/Pngs_Flat_0031_B_Leaf_L_2.png
    - assets/images/Pngs_Flat_0030_B_Leaf_L_3.png
    - assets/images/Pngs_Flat_0029_B_leaf_L_4.png
    - assets/images/Pngs_Flat_0028_B_Leaf_L_5.png
    - assets/images/Pngs_Flat_0027_B_Leaf_L_6.png

    - assets/images/Pngs_Flat_0014_F_B_Right.png
    - assets/images/Pngs_Flat_0015_F_B_Right_2.png
    - assets/images/Pngs_Flat_0013_F_Leaf_R_5.png
    - assets/images/Pngs_Flat_0012_F_Leaf_R_4.png
    - assets/images/Pngs_Flat_0011_F_Leaf_R_3.png
    - assets/images/Pngs_Flat_0010_F_Leaf_R_2.png
    - assets/images/Pngs_Flat_0009_F_Leaf_R_1.png

    - assets/images/Pngs_Flat_0035_B_Br_right.png
    - assets/images/Pngs_Flat_0036_B_Br_Right_1.png
    - assets/images/Pngs_Flat_0037_B_Br_right_2.png
    - assets/images/Pngs_Flat_0022_B_Leaf_R_5.png
    - assets/images/Pngs_Flat_0023_B_Leaf_R_4.png
    - assets/images/Pngs_Flat_0024_B_Leaf_R_3.png
    - assets/images/Pngs_Flat_0025_B_Leaf_R_2.png
    - assets/images/Pngs_Flat_0026_B_Leaf_R_1.png

    - assets/images/Loading_Screen.png
    - assets/images/Dots.png

  fonts:
    - family: HumanBeansBird
      fonts:
        - asset: assets/fonts/Bird_font.ttf

flutter_icons:
  image_path: "assets/images/icon.png"
  android: true